"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.itemregisterismData = exports.passwordGennumber = void 0;
const Getnumberuser = () => {
    let randomNumber = Math.floor(Math.random() * 1000000); // สุ่มเลขจาก 0 ถึง 999999
    return String(randomNumber).padStart(6, '0'); // แปลงเลขให้เป็นสตริงและเติม 0 ด้านหน้าถ้าต้องการ
};
const Getnumberpassword = (length) => {
    const uppercaseChars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const lowercaseChars = 'abcdefghijklmnopqrstuvwxyz';
    const digits = '0123456789';
    const allChars = uppercaseChars + lowercaseChars + digits;
    let password = '';
    password += uppercaseChars[Math.floor(Math.random() * uppercaseChars.length)];
    password += lowercaseChars[Math.floor(Math.random() * lowercaseChars.length)];
    password += digits[Math.floor(Math.random() * digits.length)];
    for (let i = 3; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * allChars.length);
        password += allChars[randomIndex];
    }
    password = password
        .split('')
        .sort(() => 0.5 - Math.random())
        .join('');
};
const itemregisterismData = () => {
    let numberuser = Getnumberuser();
    let numberpassword = Getnumberpassword(8);
    exports.passwordGennumber = numberpassword;
    const itemsdata = {
        setting: {
            casino: {
                sa: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 4,
                },
                allbet: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 2,
                },
                sexy: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 4,
                },
                dreamgame: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                prettygaming: {
                    max: 87,
                    min: 0,
                    share: 87,
                    force: 0,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                ebet: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 4,
                },
                casino_pragmaticplay: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                casino_cq9: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
            },
            game: {
                slot: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                pgslot: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                ambpoker: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                rich88: {
                    max: 87,
                    min: 0,
                    share: 87,
                    force: 0,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                spadegaming: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                iconicgaming: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                funtagaming: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                topgradegames: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                yggdrasildirect: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                slotmill: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                justplay: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                men5gaming: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                allwayspin: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                habanerogaming: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                fachai: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                simpleplay: {
                    max: 0,
                    min: 0,
                    share: 0,
                    force: 0,
                    upline: 0,
                    commission: 0,
                    saveShare: true,
                    isEnable: false,
                    settingLimit: 0,
                },
                wazdan: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                slotgroupqt: {
                    max: 87,
                    min: 0,
                    share: 87,
                    force: 0,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                booongo: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                jili: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                kagaming: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                mannaplay: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                funkygames: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                evoplay: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                pragmaticplay: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                kingmaker: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                aegaming: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                cq9: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
            },
            sport: {
                xcockfight: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                m8: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                m8live: {
                    max: 0,
                    min: 0,
                    share: 0,
                    force: 0,
                    upline: 0,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
                m8step: {
                    max: 87,
                    min: 86,
                    share: 87,
                    force: 86,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
            },
            esport: {
                xesport: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
            },
            lottery: {
                xlottery: {
                    max: 87,
                    min: 87,
                    share: 87,
                    force: 87,
                    upline: 87,
                    commission: 0,
                    saveShare: true,
                    isEnable: true,
                    settingLimit: 0,
                },
            },
        },
        settingCommission: {
            sport: {
                m8: {
                    hdpOuOeType: 'hdpOuOeA',
                    hdpOuOe: 0,
                    hdpOuOeA: 0,
                    hdpOuOeB: 0,
                    hdpOuOeC: 0,
                    hdpOuOeD: 0,
                    hdpOuOeE: 0,
                    hdpOuOeF: 0,
                    oneTwoDoubleChance: 0,
                    others: 0,
                    com4: 0,
                    com5: 0,
                    com6: 0,
                    com7: 0,
                    com8: 0,
                    com9: 0,
                },
            },
        },
        settingLimit: {
            sport: {
                m8: {
                    max1: 999999,
                    max2: 0,
                    max3: 0,
                    max4: 999999,
                    max5: 0,
                    max6: 0,
                    max7: 0,
                    lim1: 999999,
                    lim2: 0,
                    lim3: 0,
                    lim4: 999999,
                },
            },
        },
        username: `${numberuser}`,
        contact: `${numberuser}`,
        currency: 'THB',
        password: `GameAa112233`,
        creditLimit: 0,
        maxCreditLimit: 0,
        active: true,
    };
    return itemsdata;
};
exports.itemregisterismData = itemregisterismData;
//# sourceMappingURL=ItesmDataRegisterism.js.map